### ISSUE TITLE
crash on startup ;-;

### ISSUE THREAD

**Issue by ghost** [Ellpeck/Rarmor#1]
[crash-2016-09-04_22.43.03-client.txt](https://github.com/Ellpeck/Rarmor/files/453980/crash-2016-09-04_22.43.03-client.txt)

**Comment by Ellpeck** [comment]
This is a problem with BaublesStuff being hideously outdated.

**Comment by Ellpeck** [comment]
To clarify: This is a problem with the Baubles Stuff mod by zazpro having an integration feature for a _really_ outdated version of Rarmor.
Due to me and canitzp agreeing not to change the mod's id, this was bound to happen, just no one thought about it.
I messaged zazpro about it, however, please still report it to their issue tracker too if you can.

**Comment by canitzp** [comment]
You can just disable Rarmor integration in the baubles stuff config
